# SPDX-FileCopyrightText: 2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

[workspace]
members = [
  "nullboard_tools",
  "gitlab_work_units",
  "workboard_update",
  "work_unit_collection",
  "openxr_release_checklist_update",
  "cts_workboard_update",
]

resolver = "2"
