# SPDX-FileCopyrightText: 2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

targets = [
  {triple = "x86_64-unknown-linux-gnu"},
#   {triple = "x86_64-pc-windows-msvc"},
]

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
  "BSD-3-Clause", # "BSD-2-Clause",
  "BSL-1.0",
  "ISC",
  "MPL-2.0", # "MIT-0",
  "OpenSSL",
]
confidence-threshold = 0.95
copyleft = "warn"
default = "deny"
unlicensed = "deny"

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "warn"

# Keep these at the end of the file because they slightly break vscode toml parsing

# Rust fork of boringssl
[[licenses.clarify]]
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  {path = "LICENSE", hash = 0xbd0eed23},
]
name = "ring"

[[licenses.clarify]]
expression = "ISC"
license-files = [
  {path = "LICENSE", hash = 0x001c7e6c},
]
name = "webpki"
